[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bevy = "0.2.1"
bevy_prototype_character_controller = { git = "https://github.com/superdump/bevy_prototype_character_controller", branch = "main", features = [ "use_rapier" ] }
bevy_rapier3d = { git = "https://github.com/superdump/bevy_rapier", branch = "predict-for-render", features = [ "parallel", "simd-stable" ] }
building-blocks = { git = "https://github.com/bonsairobo/building-blocks", rev = "3562ad10188d67841c88fc1d9c6fecdb342873a0" }
env_logger = "0.8.1"
fnv = "1.0.7"
log = "0.4.11"
noise = "0.6.0"

[features]
default = []
profiler = [ "bevy/profiler" ]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
