[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
# bevy = "0.2.1"
bevy = { path = "../bevy" }
bevy_prototype_character_controller = { git = "https://github.com/superdump/bevy_prototype_character_controller", branch = "main", features = [ "use_rapier" ] }
bevy_rapier3d = { git = "https://github.com/superdump/bevy_rapier", branch = "predict-for-render", features = [ "parallel", "simd-stable" ] }
building-blocks = { git = "https://github.com/bonsairobo/building-blocks", rev = "7492604936dd6144948280308404ab1bb0456169" }
fnv = "1.0.7"
noise = "0.6.0"
tracing = { version = "0.1.21", optional = true }
# tracing-tracy = { version = "0.3.0", optional = true }
tracing-tracy = { path = "../rust_tracy_client/tracing-tracy", optional = true }
tracing-subscriber = { version = "0.2.14", optional = true }

[patch.crates-io]
bevy = { path = "../bevy" }
# tracy-client = { path = "../rust_tracy_client/tracy-client", optional = true }
tracy-client-sys = { path = "../rust_tracy_client/tracy-client-sys", optional = true }

[features]
default = [ "trace" ]
profiler = [ "bevy/profiler" ]
trace = [ "tracing", "tracing-tracy", "tracing-tracy/enable", "tracing-subscriber", "bevy/trace" ]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
