[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bevy = { version = "0.5", features = [ "dynamic" ] }
bevy_prototype_character_controller = { git = "https://github.com/superdump/bevy_prototype_character_controller", branch = "main", features = [ "use_rapier" ] }
bevy_rapier3d = { version = "0.9", features = [ "parallel", "simd-stable" ] }
building-blocks = "0.4"
env_logger = "0.8"
log = "0.4.11"
noise = "0.7"

[features]
default = []

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
