[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
# bevy = "0.3.0"
# bevy = { path = "../bevy" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "master" }
bevy_prototype_character_controller = { git = "https://github.com/superdump/bevy_prototype_character_controller", branch = "main", features = [ "use_rapier" ] }
bevy_rapier3d = { version = "0.5.0", features = [ "parallel", "simd-stable" ] }
building-blocks = { git = "https://github.com/bonsairobo/building-blocks", rev = "15523da" }
env_logger = "0.8.1"
noise = "0.6.0"
tracing = { version = "0.1.21", optional = true }
tracing-chrome = { git = "https://github.com/superdump/tracing-chrome", branch = "name.fields", optional = true }
tracing-subscriber = { version = "0.2.15", optional = true }

[patch.crates-io]
# bevy = { path = "../bevy" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "master" }

[features]
default = [ "trace" ]
profiler = [ "bevy/profiler" ]
trace = [ "tracing", "tracing-chrome", "tracing-subscriber" ]#, "bevy/trace" ]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1

[[example]]
name = "voxel_render"
path = "src/voxel_render.rs"

[[example]]
name = "svo_render"
path = "src/svo_render.rs"
